# Generated by Django 5.2.12 on 2026-03-19 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DDSCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'ДДС категория',
                'verbose_name_plural': 'ДДС категории',
            },
        ),
        migrations.CreateModel(
            name='DDSStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'ДДС статус',
                'verbose_name_plural': 'ДДС статусы',
            },
        ),
        migrations.CreateModel(
            name='DDSType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'ДДС тип',
                'verbose_name_plural': 'ДДС типы',
            },
        ),
        migrations.CreateModel(
            name='DDSSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='dds.ddscategory', to_field='name', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'ДДС подкатегория',
                'verbose_name_plural': 'ДДС подкатегории',
            },
        ),
        migrations.CreateModel(
            name='DDSEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, max_length=2000, verbose_name='Комментарий')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dds.ddscategory', to_field='name', verbose_name='Категория')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dds.ddsstatus', to_field='name', verbose_name='Статус')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dds.ddssubcategory', to_field='name', verbose_name='Подкатегория')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dds.ddstype', to_field='name', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'ДДС запись',
                'verbose_name_plural': 'ДДС записи',
                'default_related_name': 'entries',
            },
        ),
        migrations.AddField(
            model_name='ddscategory',
            name='parent_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='dds.ddstype', to_field='name', verbose_name='Родительский тип'),
        ),
    ]
