# Generated by Django 5.2.12 on 2026-03-19 10:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DDSCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DDSStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DDSType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DDSSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='dds.ddscategory', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='DDSEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('sum', models.DecimalField(decimal_places=2, max_digits=11)),
                ('comment', models.TextField(blank=True, max_length=2000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dds.ddscategory', to_field='name')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dds.ddsstatus', to_field='name')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dds.ddssubcategory', to_field='name')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dds.ddstype', to_field='name')),
            ],
            options={
                'default_related_name': 'entries',
            },
        ),
        migrations.AddField(
            model_name='ddscategory',
            name='parent_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='dds.ddstype', to_field='name'),
        ),
    ]
